server:
  port: 8081

spring:
  datasource:
    username: root
    password: rBq5TScFUt796Wo34d
    url: jdbc:mysql://185.133.193.251:3306/se?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  data:
    elasticsearch:
      host: 127.0.0.1
      port: 9200
      username: elasticsearch
      password: changeme

mybatis:
  type-aliases-package: com.scholar.literature.pojo
  mapper-locations: classpath:mapper/*.xml

