server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/scholar?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  data:
    elasticsearch:
      host: 127.0.0.1
      port: 9200
      username: elasticsearch
      password: changeme

mybatis:
  type-aliases-package: com.scholar.literature.pojo
  mapper-locations: classpath:mapper/*.xml

