server:
  port: 8082

spring:
  datasource:
    username: root
    password: ruangong21
    url: jdbc:mysql://185.133.193.251:3306/se?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

mybatis:
  type-aliases-package: com.scholar.profile.pojo, com.scholar.profile.dto
  mapper-locations: classpath:mapper/*.xml