server:
  port: 8084

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/scholar?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

mybatis:
  type-aliases-package: com.scholar.root.pojo
  mapper-locations: classpath:mapper/*.xml