server:
  port: 8083

spring:
  datasource:
    username: root
    password: rBq5TScFUt796Wo34d
    url: jdbc:mysql://60.205.189.66:3306/se?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

mybatis:
  type-aliases-package: com.scholar.social.repository
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      scholar:
        social:
          controller: DEBUG
          service: DEBUG
#          repository:
#            PostRepository: DEBUG

